### ISSUE TITLE
Max retries exceeded with url:  

### ISSUE THREAD

**Issue by bruceanhuifs** [flatplanet/Django_ChatGPT#4]
Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x7fe9de99f6d0&gt;: Failed to establish a new connection: [Errno 113] No route to host'))</pre>

Request Method: | POST
-- | --

4.1.7
APIConnectionError
Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe9de99f6d0>: Failed to establish a new connection: [Errno 113] No route to host'))
/root/bechatgpt/virt/lib/python3.10/site-packages/openai/api_requestor.py, line 528, in request_raw
chatbot.views.home
/root/bechatgpt/virt/bin/python
3.10.8
['/root/bechatgpt/chatgpt',  '/root/miniconda3/lib/python310.zip',  '/root/miniconda3/lib/python3.10',  '/root/miniconda3/lib/python3.10/lib-dynload',  '/root/bechatgpt/virt/lib/python3.10/site-packages']

</body>
</html>

**Comment by flatplanet** [comment]
It's telling you that you reached your max tries.  Just how many queries did you make? lol
