### ISSUE TITLE
how to solve this error" too many requests to the API." ty 

### ISSUE THREAD

**Issue by bruceanhuifs** [flatplanet/Django_ChatGPT#6]
I watched your video tutorial and used your code to build a website, and the first few days I was able to use chatgpt to answer my question, but then the following error message appeared, please tell me how to solve such an error, thank you!

Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe9dfdd5c30>: Failed to establish a new connection: [Errno 113] No route to host'))
see your tutoril and use your  code to set up the website

**Comment by flatplanet** [comment]
You made too many requests.  You just have to wait a day or so till your
count resets.

**Comment by bruceanhuifs** [comment]
dear flatplanet ty for your reply 
Is there a change in the code to fix this error?

**Comment by flatplanet** [comment]
no, it's not an error. You are only allowed so many requests via the API in
a day and you exceeded those requests.

**Comment by bruceanhuifs** [comment]
Hello flatplanet,  do you have an email address? Could you send it to me? I'll send you my website.
